Repository CowTheGreat/Real-Time-Audio-Recorder-and-Transcriber-using-Whisper-AI, pull requests merged in 2025-01, with the labels that each got.

#5 chore: refactor into multiple files
  recorder.py
  tkinter_final.py
  transcriber.py
  ui.py
Labels: SWOC, INTERMEDIATE

#22 Added requirements.txt
  requirements.txt
Labels: SWOC, BEGINNER

#27 Update requirements.txt
  requirements.txt
Labels: SWOC, BEGINNER

#25 adding browse option to gui
  recorder.py
  ui.py
Labels: SWOC, INTERMEDIATE

#26 Implemented Hotkeys
  ui.py
Labels: SWOC, BEGINNER

#32 progress indicator.py
  progress indicator.py
Labels: SWOC, BEGINNER

#43 Readme file updated
  README.md
Labels: SWOC, BEGINNER

#49 feat: Fix Audio Transcription Issues Using Librosa
  requirements.txt
  transcriber.py
Labels: SWOC, BEGINNER

#51 feat: Add File Renaming Functionality for Audio and Transcriptions
  recorder.py
  transcriber.py
  ui.py
Labels: SWOC, BEGINNER

#53 added comprehensive error handling
  recorder.py
  transcriber.py
  ui.py
Labels: SWOC, BEGINNER

#57 added support for drag n drop
  requirements.txt
  ui.py
Labels: SWOC, ADVANCE

#58 feat : Add Text Analysis Feature
  requirements.txt
  text_analyzer.py
  transcriber.py
  ui.py
Labels: SWOC, BEGINNER

#65 directly from the text file rather than the box
  .gitignore
  transcriber.py
  ui.py
Labels: SWOC, ADVANCE

#66 feat: Add Whisper model selection feature
  transcriber.py
  ui.py
Labels: SWOC, INTERMEDIATE
